sudo: required
services:
  - docker

before_install:
  - docker build -t kailashxii/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true kailashxii/react-test npm run test

after_success:
  - docker build -t kailashxii/multi_client ./client
  - docker build -t kailashxii/multi_server ./server
  - docker build -t kailashxii/multi_nginx ./nginx
  - docker build -t kailashxii/multi_worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push kailashxii/multi_client
  - docker push kailashxii/multi_server
  - docker push kailashxii/multi_nginx
  - docker push kailashxii/multi_worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "complex"
  env: "Complex-env"
  bucket_name: "elasticbeanstalk-ap-south-1-268711227061"
  bucket_path: "complex"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
